include: package:lint/analysis_options.yaml

linter:
  rules:
    #override
    unused_catch_clause: false
    unused_element: false

    #code visibility
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    avoid_relative_imports: true
    always_use_package_imports: true
    avoid_types_as_parameter_names: true
    prefer_void_to_null: true
    always_require_non_null_named_parameters: true
    avoid_init_to_null: true
    avoid_multiple_declarations_per_line: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_returning_null: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    cascade_invocations: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    empty_constructor_bodies: true
    exhaustive_cases: true
    file_names: true
    flutter_style_todos: true
    library_names: true
    non_constant_identifier_names: true
    null_closures: true
    only_throw_errors: true
    overridden_fields: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_declarations : false
    prefer_constructors_over_static_methods: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_null_aware_method_calls: true
    prefer_null_aware_operators: true
    recursive_getters: true
    tighten_type_of_initializing_formals: true
    type_init_formals: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    use_named_constants: true
    use_setters_to_change_properties: true
    void_checks: true
    sort_pub_dependencies: false

    #type strong
    always_declare_return_types: true
    annotate_overrides: true
    iterable_contains_unrelated_type: true
    unrelated_type_equality_checks: true
    list_remove_unrelated_type: true
    avoid_void_async: true
    omit_local_variable_types: true

    #widget mistakes
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true

    #project ending
    directives_ordering: false
    always_specify_types: false


analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
