name: starter_flutter
description: Starter Flutter with Firebase support

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #fvm: ^2.2.2

  #Misc
  dio: ^4.0.4
  intl: ^0.17.0
  animations: ^2.0.2
  provider: ^6.0.2
  #path_provider: ^2.0.2
  #permission_handler: ^8.1.2
  #flutter_local_notifications: ^6.0.0
  #location: ^4.2.0
  #camera: ^0.8.1+4
  #uuid: ^3.0.4
  #device_info: ^2.0.2
  #encrypt: ^5.0.0
  #shared_preferences: ^2.0.6
  #audioplayers: ^0.19.1
  #bluetooth: ^0.1.0
  #connectivity: ^3.0.6
  #open_file: ^3.2.1
  image_picker: ^0.8.4+11
  #url_launcher: ^6.0.9
  #share: ^2.0.4

  #3rd Party
  #google_maps_flutter: ^2.0.6
  #twilio_flutter: ^0.0.9
  #youtube_player_flutter: ^8.0.0

  #Authentication
  firebase_auth: ^3.3.11
  #google_sign_in: ^5.0.4
  flutter_login_facebook: ^1.4.1
  #sign_in_with_apple: ^3.0.0
  #flutter_appauth: ^1.1.0
  flutter_facebook_auth: ^4.1.2

  #Firebase
  firebase_core: ^1.13.1
  cloud_functions: ^3.2.10
  #firebase_messaging: ^10.0.3
  #firebase_remote_config: ^0.10.0+2

  #Persistence
  firebase_database: ^9.0.8
  cloud_firestore: ^3.1.10
  sqflite: ^2.0.0+3

  #Code-Utils
  equatable: ^2.0.3
  #cached_network_image: ^3.0.0
  flutter_staggered_grid_view: ^0.4.0
  #flutter_staggered_animations: ^1.0.0
  #syncfusion_flutter_charts: ^19.2.47
  #syncfusion_flutter_datepicker: ^19.2.47
  #shimmer: ^2.0.0
  #infinite_scroll_pagination: ^3.1.0
  #pull_to_refresh: ^2.0.0
  #darq: ^1.1.1

  #UI-Utils
  flutter_screenutil: ^5.3.1
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  #font_awesome_flutter: ^9.1.0
  #cupertino_icons: ^1.0.2
  #lottie: ^1.0.1

  #Models
  freezed_annotation: ^1.1.0
  google_sign_in: ^5.2.4
  #firebase_storage: ^10.2.0
  #firebase_storage: ^10.2.8
  firebase_storage: ^10.2.8
  web_socket_channel: ^2.1.0
  darq: ^1.2.1
  google_maps_flutter: ^2.1.12
  geolocator: ^8.0.1
  label_marker: ^1.0.1



dev_dependencies:
  lint: ^1.8.2
  build_runner: ^2.1.8
  # Generate with this commandline
  # flutter pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.9.2
  # Generate with this commandline
  # flutter pub run flutter_native_splash:create
  flutter_native_splash: ^2.1.1
  test_api: ^0.4.8

  #Tests
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.1.0
  #test: any

  #Models
  freezed: ^1.1.1
  json_serializable: ^6.1.5

  #State-management
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  #image_path_android: "assets/images/logo_android.png"
  #image_path_ios: "assets/images/logo_ios.png"

flutter_native_splash:
  color: "#42a5f5"
  #background_image: "assets/images/background.png"
  #image: assets/splash.png

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  #android: false
  #ios: false
  #web: false

  #android_gravity: center
  #ios_content_mode: center
  #web_image_mode: center

  #fullscreen: true
  #android12: true

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/locale/
    - assets/images/google_logo.png
    - assets/images/facebook_logo.png
    - assets/images/go&jog.png
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans/OpenSans-Bold.ttf
          style: italic